version: '3'

services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app

  mysql:
    image: mysql:8.0.30-debian
    env_file:
      - .env

  redis:
    image: redis:7.0.8-alpine
